name: xcell
favicon: null
layout_spectrum: 0.4850010429508984
typography_spectrum: 0.7628836086951196
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.831300504039973
  lightness: 0.5277496236376464
  saturation: 0.3895395980216563
  rhythmicContrast: 0.3055878928862512
purpose: []
